new Vue({
    el: '#app',
    data: {
        platform: '',
        path: '',
        conf: '',
        optionDaemon: 1,
        optionServer: 1,
        optionGen: 0,
        optionGenProcLimit: 1,
        optionEquihashSolver: 'tromp',
        optionWhiteList: [],
        tempWhitelist: '',
        customPath: 0,
        optionRpcAllowIp: '127.0.0.1',
        optionRpcUser: 'rpcuser',
        optionRpcPassword: Math.random().toString(36).slice(2),
        optionShowMetrics: 0,
        optionDataDir: ''
    },
    methods: {
        setPlatform: function (option) {
          this.platform = option
          if (this.platform == 'Linux') {
            this.path = '/home/user/.hush'
          } else if (this.platform == "Mac OS") {
            this.path = ''
          } else {
            this.path = 'C:\\Users\\your_username\\AppData\\Roaming\\Hush'
          }
          $('.platform-banner').show()
        },
        showPathInput: function () {
          $('#paths').toggle()
        },
        pickPath: function () {

        },
        showThreads: function () {
          $('#threads').toggle()
        },
        decreaseThreads: function () {
          if (this.optionGenProcLimit != 0) {
            this.optionGenProcLimit--
          }
        },
        increaseThreads: function () {
          this.optionGenProcLimit++
        },
        addWhiteList: function (value) {
          this.optionWhiteList.push(value)
          this.tempWhitelist = ''
        },
        removeWhiteListItem: function (item) {
          console.log(item)
          var index = this.optionWhiteList.indexOf(item)
          this.optionWhiteList.splice(index, 1)
        },
        compile: function () {
          var currentdate = new Date();
          var compileTime = currentdate.getDate() + "/"
                + (currentdate.getMonth()+1)  + "/"
                + currentdate.getFullYear() + " @ "
                + currentdate.getHours() + ":"
                + currentdate.getMinutes() + ":"
                + currentdate.getSeconds()
          this.conf =
            "# HUSH Configuaration File<br /><br /># This file has been automatically generated by Hush Config Generator. It may be further cutsomized by hand only.<br /><br /># Creation date: " + compileTime + "<br /><br /># The rpcuser/rpcpassword are used for the local call to hushd. The rpcpassword was randomly set.<br /><br /># Start Hush Configuration<br /><br />daemon=" + this.optionDaemon + "<br />server=" + this.optionServer + "<br />whitelist=" + this.optionWhiteList + "<br />rpcallowip=" + this.optionRpcAllowIp + "<br />rpcuser=" + this.optionRpcUser + "<br />rpcpassword=" + this.optionRpcPassword + "<br />"
          if (this.customPath == 1) {
            this.conf = this.conf + "<br />datadir=" + this.optionDataDir
          }
          if (this.optionGen == 1) {
            this.conf = this.conf + "<br />gen=1<br />genproclimit=" + this.optionGenProcLimit
          }
          if (this.optionShowMetrics == 1) {
            this.conf = this.conf + "<br /><br />showmetrics=1"
          }
          $('#profile').show()
        }
      }
});
